name: Publish

on:
  push:
    branches:
      - main

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

concurrency:
  group: "teahouse"
  cancel-in-progress: false

jobs:
  publish:
    environment:
      name: teahouse
      url: https://buddys.technicallycompetent.com

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: move
        run: |
          mkdir dist
          ./process.js > dist/index.html

      - name: Upload
        uses: teahouse-hosting/upload@trunk
        with:
          domain: test.downloadacar.com
          root: dist
